/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PintoraPreview {
        /**
          * pintora api
         */
        "pintora": any;
        "refresh": () => Promise<void>;
        "showSource": boolean;
    }
}
declare global {
    interface HTMLPintoraPreviewElement extends Components.PintoraPreview, HTMLStencilElement {
    }
    var HTMLPintoraPreviewElement: {
        prototype: HTMLPintoraPreviewElement;
        new (): HTMLPintoraPreviewElement;
    };
    interface HTMLElementTagNameMap {
        "pintora-preview": HTMLPintoraPreviewElement;
    }
}
declare namespace LocalJSX {
    interface PintoraPreview {
        /**
          * pintora api
         */
        "pintora"?: any;
        "showSource"?: boolean;
    }
    interface IntrinsicElements {
        "pintora-preview": PintoraPreview;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pintora-preview": LocalJSX.PintoraPreview & JSXBase.HTMLAttributes<HTMLPintoraPreviewElement>;
        }
    }
}
